# Generated by Django 5.1.4 on 2024-12-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_supplierprofile_shopownerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='supplier',
            new_name='shop_owner',
        ),
    ]
