# Generated by Django 5.1.4 on 2024-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_supplier_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain_name',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
