# Generated by Django 5.1.4 on 2024-12-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_shops_product_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shopownerprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'shop_owner')},
        ),
    ]
