# Generated by Django 5.1.4 on 2024-12-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='phone',
        ),
    ]
