# Generated by Django 5.1.4 on 2024-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_shopownerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='search',
            field=models.BooleanField(default=False),
        ),
    ]
