# Generated by Django 5.1.4 on 2024-12-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
